name: Prettier

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  prettier:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Prettier JS
      run: |
        npm install prettier@3.0.0
        npx prettier --trailing-comma none --check public/**/*.js public/**/*.css
