name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '35 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v7
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-pr-stale: 60
        days-before-issue-stale: 30
        days-before-close: 14
        stale-issue-message: 'Could you update this issue?'
        stale-pr-message: 'You should update this pull request by commenting on it. Otherwise the PR will be closed in 14 days.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
